### ISSUE TITLE
Big Gap in YouTube Home Feed

### ISSUE THREAD

**Issue by arichornlover** [PoomSmart/YTUnShorts#1]
https://user-images.githubusercontent.com/78001398/208324356-daae1a2a-c25d-489a-a99b-a68d89771928.MOV
I don’t know what it was caused but it removed the shorts menu and left a big gap in the home feed. and I do have MiRO’s YTNoShorts disabled in the uYou settings.

**Comment by NguyenASang** [comment]
@PoomSmart Can we remove the gap ? Your tweak has the same bug as the Miro's one.

**Comment by moritz-t-w** [comment]
Can confirm this happens without MiRO's stuff installed
